"""Declarative registry of standard CRUD commands generated by the command factory."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

from cribl_cli.api.endpoint_factory import EndpointConfig

Operation = Literal["list", "get", "create", "update", "delete"]
ALL_OPS: list[Operation] = ["list", "get", "create", "update", "delete"]


@dataclass
class CommandRegistration:
    name: str
    endpoint: EndpointConfig
    operations: list[Operation] = field(default_factory=lambda: list(ALL_OPS))


REGISTRY: list[CommandRegistration] = [
    # Group-scoped (full CRUD)
    CommandRegistration("parsers", EndpointConfig("group", "system/parsers")),
    CommandRegistration("schemas", EndpointConfig("group", "schemas")),
    CommandRegistration("regex", EndpointConfig("group", "lib/regex")),
    CommandRegistration("grok", EndpointConfig("group", "lib/grok")),
    CommandRegistration("event-breakers", EndpointConfig("group", "lib/breakers")),
    CommandRegistration("global-vars", EndpointConfig("group", "lib/vars")),
    CommandRegistration("db-connections", EndpointConfig("group", "lib/db-connections")),
    CommandRegistration("secrets", EndpointConfig("group", "system/secrets")),
    CommandRegistration("credentials", EndpointConfig("group", "system/credentials")),
    CommandRegistration("collectors", EndpointConfig("group", "collectors")),
    CommandRegistration("conditions", EndpointConfig("group", "lib/conditions")),
    CommandRegistration("parquet-schemas", EndpointConfig("group", "lib/parquet-schemas")),
    CommandRegistration("protobuf-libs", EndpointConfig("group", "lib/protobuf-libs")),
    CommandRegistration("sds-rules", EndpointConfig("group", "lib/sds/rules")),
    CommandRegistration("sds-rulesets", EndpointConfig("group", "lib/sds/rulesets")),
    CommandRegistration("appscope", EndpointConfig("group", "lib/appscope")),
    # Group-scoped (limited)
    CommandRegistration("certificates", EndpointConfig("group", "system/certificates"), ["list", "get", "create", "delete"]),
    CommandRegistration("samples", EndpointConfig("group", "system/samples"), ["list", "get", "create", "delete"]),
    CommandRegistration("scripts", EndpointConfig("group", "system/scripts"), ["list", "get", "create", "delete"]),
    CommandRegistration("lookups", EndpointConfig("group", "system/lookups")),
    # packs: hand-written command in commands/packs.py (export, install, upgrade)
    CommandRegistration("executors", EndpointConfig("group", "executors"), ["list", "get"]),
    CommandRegistration("hmac-functions", EndpointConfig("group", "lib/hmac"), ["list", "get"]),
    CommandRegistration("functions", EndpointConfig("group", "system/functions"), ["list", "get"]),
    # Global-scoped (full CRUD)
    CommandRegistration("users", EndpointConfig("global", "system/users")),
    CommandRegistration("roles", EndpointConfig("global", "system/roles")),
    CommandRegistration("teams", EndpointConfig("global", "system/teams")),
    CommandRegistration("policies", EndpointConfig("global", "system/policies")),
    CommandRegistration("banners", EndpointConfig("global", "system/banners")),
    CommandRegistration("encryption-keys", EndpointConfig("global", "system/encryption-keys")),
    CommandRegistration("notification-targets", EndpointConfig("global", "notification-targets")),
    CommandRegistration("workspaces", EndpointConfig("global", "workspaces")),
    # Global-scoped (limited)
    CommandRegistration("messages", EndpointConfig("global", "system/messages"), ["list", "get", "create", "delete"]),
    CommandRegistration("licenses", EndpointConfig("global", "system/licenses"), ["list", "get"]),
    CommandRegistration("subscriptions", EndpointConfig("global", "system/subscriptions"), ["list", "get"]),
    CommandRegistration("outposts", EndpointConfig("global", "system/outposts"), ["list", "get"]),
    # alerts: hand-written command in commands/alerts.py (filters saved searches to scheduled ones)
    CommandRegistration("feature-flags", EndpointConfig("global", "system/feature-flags"), ["list", "get", "update", "delete"]),
    CommandRegistration("ai-settings", EndpointConfig("global", "system/ai-settings"), ["list", "get", "update", "delete"]),
    CommandRegistration("auth-settings", EndpointConfig("global", "system/auth", singleton=True), ["get", "update"]),
    CommandRegistration("git-settings", EndpointConfig("global", "system/git-settings", singleton=True), ["get", "update"]),
    # Search-scoped
    CommandRegistration("macros", EndpointConfig("search", "macros")),
    CommandRegistration("dataset-providers", EndpointConfig("search", "dataset-providers")),
    CommandRegistration("dashboard-categories", EndpointConfig("search", "dashboard-categories")),
    CommandRegistration("trust-policies", EndpointConfig("search", "trust-policies")),
    CommandRegistration("datatypes", EndpointConfig("search", "datatypes")),
    CommandRegistration("datasets", EndpointConfig("search", "datasets")),
    CommandRegistration("dashboards", EndpointConfig("search", "dashboards"), ["list", "get", "create", "delete"]),
    CommandRegistration("saved-searches", EndpointConfig("search", "saved")),
    CommandRegistration("notifications", EndpointConfig("group", "notifications")),
    CommandRegistration("alert-monitors", EndpointConfig("group", "alert/monitors")),
    CommandRegistration("usage-groups", EndpointConfig("search", "usage-groups"), ["list", "get"]),
    # Lake-scoped
    CommandRegistration("lake-datasets", EndpointConfig("lake", "datasets")),
    CommandRegistration("storage-locations", EndpointConfig("lake", "storage-locations")),
]
